### ISSUE TITLE
topminecraftmods.com

### ISSUE THREAD

**Issue by damianea103** [StopModReposts/Illegal-Mod-Sites#119]
This site seems very suspicious but the weird thing is that for two of the mods it links to the original author’s page, for one it downloads an exe and for the other two it leads to some ad website i’ve never seen used. So 3 mods stolen and two relinked.

**Comment by bilde2910** [comment]
Thank you for the submission! [Malware was found](https://www.virustotal.com/#/file/736984ed0d84bd7baf7a9789f100a527f45d7847eab7853a58336a3c5a171e78/detection) on this domain. An additional site (shadersmod.net) was also found and added to the list. These sites try to trick people into downloading mods that are actually viruses. It's a good thing that these end up on the list of dangerous sites.

**Comment by sekwah41** [comment]
As one of the mod authors that use this site atm I am in contact with the owner of the site. I did note to him when I started that it is flagged as malware which I will follow up. I ran the applications in a sandbox and the only data that seems to be changed is a general installer like when you download java or other applications and it asks if you want to download McAfee or other things.

My mod is listed at https://www.topminecraftmods.com/mods/naruto-mod/

I was originally skeptical of the site until I warned my friend of the site and he said he had actually worked with the owner on a past project as well as had his stuff there voluntarily.

Its not really proof but another point is if this really was a redistribution site then why would it have so few mods? Contact some of the authors and you will get the same sort of stories.

Id suggest removing the redistribution rating but keeping the miscellaneous for now and I will see what I can do. The site is pretty good, legit and has the highest payout.

Also if you look at https://www.topminecraftmods.com/mods/pams-harvestcraft/ the downloads are wrapped in the installers which give a higher payout rate but anyone using those is by request rather than because thats how the site works. For example if you download one of mine it is the default jar file which I think the main ad atm wraps the jar file in that downloader seen on pams.

**Comment by sekwah41** [comment]
Also if mods arn't approved by the authors themselves they arnt downloads or links with ads, example:
https://www.topminecraftmods.com/mods/optifine/

**Comment by sekwah41** [comment]
I see the issue is still open but example of how it is not redistribution without permission https://www.topminecraftmods.com/mods/optifine/ if you click download it redirects to their own download page which it should probably use their adf.ly links but it doesnt display any ads when taking you there and it is hosted on the optifine website.

If you are going to keep the redistribution rating please actually use evidence rather than a slight suspicion. This all seems based off "This site seems very suspicious but the weird thing is that for two of the mods it links to the original author’s page" and even there hes saying its wierd it links to the actual mod authors sites so im confused with the high rating.

I just saw someone post a screenshot of another site on a discord and remembered that this was still an ongoing issue

**Comment by danielm59** [comment]
Definitely a dodgy site, https://www.topminecraftmods.com/mods/pams-harvestcraft/ has downloads as a .exe rather than a .jar. it does not got to an official source of the mod.

**Comment by sekwah41** [comment]
The guy is shutting down the site anyway but that was apparently actually at the request of pams harvest as it has a higher payout and MatrexsVigil makes a living off her mods.

**Comment by bilde2910** [comment]
I've reached out to mod developers about this and gotten general feedback that they have revoked their permission to offer .exe downloads long ago but the site has refused to take them down. Most or all of the .exe downloads are the same size, and they [flag as dangerous](https://www.virustotal.com/#/file/4825bb332dd6a9e2bb413dd4493d806fa994e5a072c9644f67075c94d1f3d5eb/detection) with several high-profile antivirus solutions including Microsoft, ESET, Malwarebytes and Sophos. The download links further redirect to "netb.ee" instead of official download links for many of those which don't use .exe files. As such the site is considered dangerous and the rating shall stand.

**Comment by sekwah41** [comment]
This sites been abandoned by the creator for about half a year now xD nice to see you guys are keeping on top of all this. The whole point originally was never the downloads but rather the rating of redistribution which as far as I could tell everyone had given permission when the files were actually hosted there.

Nice to see such a useless notification on my github after all this time xD
