### ISSUE TITLE
A list of sites

### ISSUE THREAD

**Issue by NicosaurusRex99** [StopModReposts/Illegal-Mod-Sites#146]
These sites all stole some of my mods
-=-=-=-==-=-==-=-=-=- SCUM of the world -=-=-=-==-=-==-=-=-=-
http://minecraft-forum.net/minecraft-mods-downloads/1-10-2-thousand-degree-knife-mod-download/#.WJXDrfl94b5
http://niceminecraft.net/thousand-degree-knife-mod/
https://minecraftmodz.com/thousand-degree-knife-mod-1-10-2/
https://minecraftmodz.com/thousand-degree-knife-mod-1-10-2-2/
http://minecraftea.com/thousand-degree-knife-mod-cuchillo-a-1000-grados-en-minecraft-minecraft-mod-1-10-2/
http://www.9minecraft.net/thousand-degree-knife-mod/
http://www.minecraftplus.org/thousand-degree-knife-mod-1-10-2-download.html
http://www.mc-mod.net/thousand-degree-knife-mod/
http://mod-minecraft.net/thousand-degree-knife-mod/
http://www.mc-vn.net/thousand-degree-knife-mod/
https://minecraftmodz.com/thousand-degree-knife-mod/
https://minecraftmodz.com/thousand-degree-knife-mod-2-2/
http://minecraft-forum.net/minecraft-mods-downloads/1-11-2-thousand-degree-knife-mod-download/
http://minecraftea.com/thousand-degree-knife-mod-cuchillo-a-1000-grados-en-minecraft-minecraft-mod-1-10-2/
http://www.yourminecraft.com/thousand-degree-knife-mod-minecarft/ <---------- extra scummy, want me to pay $10 to download my own mod (atleast they did like a year ago)
https://fileversal.com/download-just-another-ruby-mod

**Comment by RedstoneParadox** [comment]
Some of those already are on the list.

**Comment by bilde2910** [comment]
Thanks for your submission. There are a lot of sites here which are already on the list, so I'd appreciate checking the list first to make sure that your sites aren't already listed. It saves a lot of extra work in reviewing sites. I added a handful of your sites; I couldn't reach `minecraftea com` due to connection timeouts, so I'll have to pass on that one.

Note that the license for the mod you used as the primary example here allows redistribution. So you do not have any legal recourse or right to take those down:

>2. GRANT OF RIGHTS  
a) Subject to the terms of this Agreement, each Contributor hereby grants  
>Recipient a non-exclusive, worldwide, royalty-free copyright license to  
>reproduce, prepare derivative works of, publicly display, publicly  
>perform, distribute and sublicense the Contribution of such Contributor,  
>if any, and such derivative works, in source code and object code form.  

I added the sites anyway because they also host content which does not have such a license.
