### ISSUE TITLE
9minecraft.net IS GONE!!

### ISSUE THREAD

**Issue by staj-d** [StopModReposts/Illegal-Mod-Sites#173]
9minecraft<.>net seems to have been shut down!! 😃 😃 😃 😃 😃

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/52527138-7c5f2100-2c91-11e9-939c-7a87d1b34f64.png)
Definitely not?

**Comment by arduino5144** [comment]
NO! They have great mods!

**Comment by itsmeow** [comment]
@arduino5144 
http://stopmodreposts.org
Please read this. 9minecraft.net does not OWN their mods. They are not allowed to even have them. If you want "great mods" please use Curse.
https://minecraft.curseforge.com/mc-mods

**Comment by bilde2910** [comment]
9minecraft engages in illegal activity and is harmful to the modding community. When you download from them, you do not support the people who made the mods; instead you give free money to a guy in Vietnam who steals what modders made in order to earn money himself. (Imagine drawing something, then the guy next to you steals the drawing and tells everyone he made it, and gets all the fame.) You also risk getting broken/old versions of mods that can crash your game. Always use a site like CurseForge ([link here](https://minecraft.curseforge.com/mc-mods)) instead.

**Comment by ohlookitsderpy** [comment]
Sadly they're back up now

**Comment by staj-d** [comment]
I guess I caught them down by random.

**Comment by SquidO2400** [comment]
> OWN

Modrinth is better
