### ISSUE TITLE
Add translation language

### ISSUE THREAD

**Issue by Nyuhnyash** [StopModReposts/Illegal-Mod-Sites#178]
I would like to translate the StopModReposts project into Russian. Please add it to the translation portal.

**Comment by bilde2910** [comment]
Russian has been added to the Crowdin project page here: https://crowdin.com/project/stop-mod-reposts

Thanks for willing to contribute to the project!

**Comment by Nyuhnyash** [comment]
Done 😫

**Comment by bilde2910** [comment]
Thanks a lot for your contribution! Everything looks really good, but there's one thing I'd like to ask. In the [storedesc.txt file](https://crowdin.com/translate/stop-mod-reposts/14/en-ru), there is a string in the second last paragraph that contains an email address. Is there some way to avoid using a . and @ in the translation? E.g. for English, instead of the following - "test@example.com" - a better idea may be to do this: "test (at) example (dot) com" - is something similar possible in Russian? I'm not familiar with Russian, so I don't know how it would best be done. This is meant as a spam protection measure.

Thank you for everything else! I'll make sure to include it in the next update :+1:
