### ISSUE TITLE
https://www.optifined.com/

### ISSUE THREAD

**Issue by Martinternet** [StopModReposts/Illegal-Mod-Sites#511]
[**What site do you want to be added?**] 
https://www.optifined.com/

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Do you have anything else worth mentioning?**
It attempts to imitate the real website for the Optifine mod, utilising a stolen logo from the real Optifine site (Optifine.net) in an attempt to lure people, and whenever I open the link, the antivirus program which I use flags it as containing malware. This may require investigation, as I simply do not want to put my computer at further risk. Cheers.

**Comment by Martinternet** [comment]
Oh, okay. Thanks. I was unable to verify whether or not it was a reupload site, as I was unwilling to look further, because, as you can imagine, I was unwilling to put my computer at further risk. Thanks for the reply.

**Comment by Brandonbr1** [comment]
please close  this 

this website is  not a repost site is it optifine second website that is no longer updated you can go on optifine reddit and you will see that this website is an official

**Comment by Ari-RERA-43** [comment]
@Brandonbr1
https://optifined.net is the official backup site, https://optifined.com is not. 

<he>

Also, it appears that this site doesn't send you to the official site anymore, it just gives the user malware.

**Comment by GEOEGII555** [comment]
![изображение](https://user-images.githubusercontent.com/57674559/180178594-25370875-b1bd-4417-805a-8339da5bd336.png)
It doesn't uses stolen logo, but when downloading it leads to viruses

**Comment by GEOEGII555** [comment]
![изображение](https://user-images.githubusercontent.com/57674559/180178732-f350e510-7bb3-44f1-8404-1e10106d53c8.png)
Re-uploaded mod files

**Comment by Ari-RERA-43** [comment]
> ![изображение](https://user-images.githubusercontent.com/57674559/180178594-25370875-b1bd-4417-805a-8339da5bd336.png)
> 
> It doesn't uses stolen logo, but when downloading it leads to re-uploaded mod files

The site has changed significantly since the last comment on this post. It used to use the official OptiFine logo. 

> ![изображение](https://user-images.githubusercontent.com/57674559/180178732-f350e510-7bb3-44f1-8404-1e10106d53c8.png)
> 
> Re-uploaded mod files

As I said before, I don't support what this site is doing (rather, I'm quite against it), it's technically not redistributing OptiFine. Those download buttons, when they go to a download for OptiFine at all, go to the official download page. When they don't, they sometimes go to malware, but that malware is not claiming to be OptiFine

<hr>

I don't know if SMR includes sites like this on the list. If they do, I'm all for having this site added (I didn't make that clear in my previous comments).
